onlinepizzas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("register", views.register_view, name="register_view"),
    path("login", views.login_view, name="login_view"),
    path("menu", views.menu_view, name="menu_view"),
    path("confirm_order", views.confirm_order, name="confirm_order"),
    path("order", views.place_order, name="place_order"),
    path("my_orders", views.user_orders_view, name="user_orders_view"),
    path("logout", views.logout_view, name="logout_view"),
    path("feedback", views.feedback_view, name="feedback_view"),
    path("pdf_orders", views.render_to_pdf, name="print_pdf")
]

yumpizza/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("onlinepizzas.urls")),
    path('admin/', admin.site.urls),
]

onlinepizzas/models.py
from pyexpat import model

from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from yumpizza import settings


class Pizza(models.Model):
    name = models.CharField(max_length=60, unique=True)
    description = models.CharField(max_length=250)
    price = models.IntegerField(default=0, editable=True)
    mass = models.IntegerField()

    class Meta:
        db_table = "pizza"
        managed = True

    def __str__(self):
        return self.name


class Drink(models.Model):
    name = models.CharField(max_length=60, unique=True)
    description = models.CharField(max_length=250)
    price = models.IntegerField(default=0, editable=True)

    class Meta:
        db_table = "drink"
        managed = True

    def __str__(self):
        return self.name


class Snack(models.Model):
    name = models.CharField(max_length=60, unique=True)
    description = models.CharField(max_length=250)
    price = models.IntegerField(default=0, editable=True)

    class Meta:
        db_table = "snack"
        managed = True

    def __str__(self):
        return self.name


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="member", on_delete=models.CASCADE)
    order_timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "order"
        managed = True

    def __str__(self):
        return str(self.pk)


class OrderPizza(models.Model):
    itemId = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    orderId = models.ForeignKey(Order, on_delete=models.CASCADE)
    Qty = models.IntegerField(default=1)

    def __str__(self):
        return str(self.orderId)


class OrderDrink(models.Model):
    itemId = models.ForeignKey(Drink, on_delete=models.CASCADE)
    orderId = models.ForeignKey(Order, on_delete=models.CASCADE)
    Qty = models.IntegerField(default=1)

    def __str__(self):
        return str(self.orderId)


class OrderSnack(models.Model):
    itemId = models.ForeignKey(Snack, on_delete=models.CASCADE)
    orderId = models.ForeignKey(Order, on_delete=models.CASCADE)
    Qty = models.IntegerField(default=1)

    def __str__(self):
        return str(self.orderId)


class UserManager(BaseUserManager):
    def create_user(self, number, email, first_name, last_name, birthday, password=None):
        if number is None:
            raise TypeError("Username cannot be blank")
        if email is None:
            raise TypeError("Email cannot be blank")
        user = self.model(number=number, email=self.normalize_email(email), first_name=first_name, last_name=last_name,
                          birthday=birthday)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, number, email, first_name, last_name, birthday, password):
        if password is None:
            raise TypeError("Enter password")
        user = self.create_user(number, email, first_name, last_name, birthday, password)
        user.is_superuser = True
        user.is_staff = True
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    number = models.CharField(db_index=True, max_length=12, unique=True)
    email = models.EmailField(db_index=True, unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50)
    birthday = models.DateField()
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    USERNAME_FIELD = 'number'
    REQUIRED_FIELDS = ['email', 'birthday', 'first_name', 'last_name']
    objects = UserManager()

    class Meta:
        managed = True
        db_table = "users"

    def __str__(self):
        return self.number


class Position(models.Model):
    title = models.CharField(db_index=True, unique=True, max_length=50)
    number_of_vacancy = models.IntegerField()
    payment = models.IntegerField()

    def __str__(self):
        return self.title


class Workers(models.Model):
    last_name = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50)
    birthday = models.DateField()
    employment_date = models.DateField()
    number = models.CharField(db_index=True, unique=True, max_length=12)
    employment_history_number = models.CharField(max_length=30)
    email = models.EmailField(db_index=True, unique=True)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)

    def __str__(self):
        return self.number


class FeedBack(models.Model):
    text = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)


class Product(models.Model):
    title = models.CharField(max_length=50, unique=True)
    amount = models.IntegerField()

    def __str__(self):
        return self.title


class Recipe(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.DO_NOTHING)
    ingredient = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    mass = models.IntegerField()

    def __str__(self):
        return self.pizza


class DecommissionedProduct(models.Model):
    amount = models.IntegerField()
    dateOfDecommission = models.DateField()
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.product


class Distributor(models.Model):
    phone = models.CharField(max_length=12, unique=True, db_index=True)
    email = models.TextField()
    productType = models.TextField()

    def __str__(self):
        return self.phone


class DistributorOrder(models.Model):
    price = models.IntegerField()
    estimatedDate = models.DateField()
    orderDate = models.DateField(auto_now_add=True)
    orderStatus = models.CharField(max_length=50)
    lastDeliveryDate = models.DateField()
    distributor = models.ForeignKey(Distributor, on_delete=models.DO_NOTHING)
    orderContent = models.TextField()

    def __str__(self):
        return self.orderDate


class Vacancy(models.Model):
    free = models.IntegerField()
    payment = models.IntegerField()
    position = models.ForeignKey(Position, on_delete=models.CASCADE)

onlinepizzas/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from onlinepizzas.models import User
from django.contrib.auth.forms import UserCreationForm
import datetime


def only_int(value):
    if not value.isdigit():
        raise ValidationError('Введите верный номер')
    if len(value) != 11:
        raise ValidationError('Введите 11 цифр, начиная с 8')


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    number = forms.CharField(required=True, validators=[only_int])
    birthday = forms.DateField(required=True, widget=forms.SelectDateWidget(
        years=range(int(datetime.datetime.now().year - 90), int(datetime.datetime.now().year + 1))))

    class Meta:
        model = User
        fields = (
            'number',
            'first_name',
            'last_name',
            'middle_name',
            'birthday',
            'email',
            'password1',
            'password2'
        )
        labels = {
            'number': 'Номер',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'middle_name': 'Отчество',
            'birthday': 'Дата рождения',
            'email': 'E-Mail',
            'password1': 'Пароль',
            'password2': 'Подтвердите пароль'
        }
        widgets = {
            'birthday': forms.DateField
        }

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return User

onlinepizzas/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm

from django.contrib.auth.decorators import login_required

from .models import *
from .forms import *


# Create your views here.
def index(request):
    return render(request, 'welcome.html')


def login_view(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = AuthenticationForm(data=request.POST)
            username = form.data["number"]
            password = form.data["password"]
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                if next is not None:
                    return redirect("menu_view")
                else:
                    return redirect("index")
            else:
                return render(request, "welcome.html", {"message": "Неверный номер или пароль"})
        else:
            form = AuthenticationForm()
        context = {"form": form}
        return render(request, 'registration/login.html', context)
    else:
        return redirect("index")


def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("index")


def register_view(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["number"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("index")
    else:
        form = RegistrationForm()
    context = {"form": form}
    return render(request, 'register.html', context)


@login_required
def menu_view(request):
    pizzas = Pizza.objects.all()
    snacks = Snack.objects.all()
    drinks = Drink.objects.all()
    return render(request, 'menu.html', {"pizzas": pizzas, "drinks": drinks, "snacks": snacks})


@login_required
def confirm_order(request):
    quantities_pizza = request.POST.getlist('qty_pizza')
    quantities_drink = request.POST.getlist('qty_drink')
    quantities_snack = request.POST.getlist('qty_snack')
    pizzas = Pizza.objects.all()
    snacks = Snack.objects.all()
    drinks = Drink.objects.all()
    ordered_pizzas = []
    ordered_drinks = []
    ordered_snacks = []
    ordered_pizzas_quantities = []
    ordered_drinks_quantities = []
    ordered_snacks_quantities = []

    # prices = request.POST.getlist('price')
    pizza_totals = []
    drink_totals = []
    snack_totals = []
    for item, qty in zip(pizzas, quantities_pizza):
        if int(qty) > 0:
            ordered_pizzas.append(item)
            ordered_pizzas_quantities.append(int(qty))
            pizza_totals.append(item.price * int(qty))
    for item, qty in zip(drinks, quantities_drink):
        if int(qty) > 0:
            ordered_drinks.append(item)
            ordered_drinks_quantities.append(int(qty))
            drink_totals.append(item.price * int(qty))
    for item, qty in zip(snacks, quantities_snack):
        if int(qty) > 0:
            ordered_snacks.append(item)
            ordered_snacks_quantities.append(int(qty))
            snack_totals.append(item.price * int(qty))

    return render(request, 'order_confirmation.html', {"pizzas_summary": zip(ordered_pizzas, ordered_pizzas_quantities,
                                                                             pizza_totals),
                                                       "drinks_summary": zip(ordered_drinks,
                                                                             ordered_drinks_quantities, drink_totals),
                                                       "snacks_summary": zip(ordered_snacks, ordered_snacks_quantities,
                                                                             snack_totals),
                                                       "grand_total": sum(pizza_totals) + sum(drink_totals) +
                                                                      sum(snack_totals) + 100})


@login_required
def place_order(request):
    pizza_quantities = request.POST.getlist('pizza_qty')
    drink_quantities = request.POST.getlist('drink_qty')
    snack_quantities = request.POST.getlist('snack_qty')
    pizzas = request.POST.getlist('pizza')
    drinks = request.POST.getlist('drink')
    snacks = request.POST.getlist('snack')
    order = Order(user=request.user)
    order.save()

    for item, qty in zip(pizzas, pizza_quantities):
        pizza = Pizza.objects.filter(name=item)
        order_pizza = OrderPizza(itemId=pizza.first(), orderId=order, Qty=qty)
        order_pizza.save()
    for item, qty in zip(drinks, drink_quantities):
        drink = Drink.objects.filter(name=item)
        order_drink = OrderDrink(itemId=drink.first(), orderId=order, Qty=qty)
        order_drink.save()
    for item, qty in zip(snacks, snack_quantities):
        snack = Snack.objects.filter(name=item)
        order_snack = OrderSnack(itemId=snack.first(), orderId=order, Qty=qty)
        order_snack.save()

    return render(request, 'order.html')

orders_context = {}

@login_required
def user_orders_view(request):
    orders = Order.objects.filter(user=request.user)
    my_orders = {}
    for item in orders:
        orders_pizza = OrderPizza.objects.filter(orderId=item)
        orders_drinks = OrderDrink.objects.filter(orderId=item)
        orders_snack = OrderSnack.objects.filter(orderId=item)
        my_orders[f"{item}"] = {"date": item.order_timestamp, "pizzas": orders_pizza, "drinks": orders_drinks,
                                "snacks": orders_snack}

    context = {"orders": my_orders}
    global orders_context
    orders_context = context
    return render(request, 'my_orders.html', context)


# @login_required
def feedback_view(request):
    if request.POST:
        text = request.POST.getlist('comment')[0]
        feedback = FeedBack.objects.filter(user=request.user).first()
        if feedback:
            feedback.text = text
        else:
            feedback = FeedBack(text=text, user=request.user)
        feedback.save()
    feedbacks = FeedBack.objects.all()
    feedback_list = {}
    for item in feedbacks:
        feedback_list[f"{item.user.first_name}"] = {"text": item.text}
    context = {"feedbacks": feedback_list}
    return render(request, 'feedback.html', context)


from xhtml2pdf import pisa
from django.template.loader import get_template
from django.views import View


def render_to_pdf(request, context={}):
    global orders_context
    context = orders_context
    template = get_template('my_orders.html')
    html = template.render(context)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="Orders.pdf"'
    pdf = pisa.CreatePDF(html, dest=response, )
    if not pdf.err:
        return response
    return None

onlinepizzas/templates/feedback.html
{% extends "layout.html" %}

{% block body %}
<div class="container text-center" style="font-variant-caps: all-small-caps;">
    <div style="padding-bottom: 15px;font-size: x-large">Отзывы</div>
{% if user.is_authenticated %}
    <form name="feedback_input" method="post">
    {% csrf_token %}
    <b>Оставьте отзыв!</b><br>
   <textarea name="comment" cols="80" rows="5"></textarea><br>
    <input type="submit" value="Отправить">
 </form>
{% endif %}
    <table>
                <tbody>
                    {% for feedback,vals in feedbacks.items %}
                        <tr>
                            <td>
                                <a>{{feedback}}</a><br>
                                <a>{{vals.text}}</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
    </table>

    <div>

    </div>
</div>

{% endblock %}

onlinepizzas/templates/layout.html
<!DOCTYPE html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>
        Вкусная пицца
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script type = "text/javascript"
      src = "https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>


    <style>
        table, th, td {
            border: 1px solid black;
        }
        th, td{
            padding: 0 15px;
        }
        table{
            font-variant-caps: all-small-caps;
            margin: 50px auto auto auto;

        }
        .fb_btn{

        }
        @font-face { font-family: Arial; src: url("D:\GitHub\yumpizza\static\fonts\arial.ttf"); }
        div {font-family: Arial;}
    </style>

    <script>

        $(function() {
            $('.qty').on('change', function() {
                let pizza_added = false;
                $('.qty').each(function (){
                    if($(this).val() > 0){
                        pizza_added = true;
                        return false;
                    }
                })
                if(pizza_added){
                    $('#placeorder').prop('disabled', false);
                }
                else{
                    $('#placeorder').prop('disabled', true)
                }
                });
        })

    </script>

</head>
<body>
{% if user.is_authenticated %}
    <div class="navbar sticky-top navbar-dark bg-dark">
        <div class="navbar-brand"> Добро пожаловать, комрад  <span style='color: #119c1e;'>{{ user.first_name }}!!</span>:</div>
        <div>
            <a href="{% url "menu_view" %}">
                <button class="btn mx-1 my-xl-0 my-2">Меню</button>
            </a>
            <a href="{% url "logout_view" %}">
                <button class="btn mx-1 my-xl-0 my-2" type="button">Выйти</button>
            </a>
            <a href="{% url "user_orders_view" %}">
                <button class="btn ml-1 my-xl-0 my-2" type="button" title="All orders">Заказы</i>
                </button>
            </a>
            <a href="{% url "feedback_view" %}">
                <button class="btn mx-1 my-xl-0 my-2" type="button">Отзывы</button>
            </a>
            </div>
    </div>
{% else %}
    <div class="navbar sticky-top navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Добро пожаловать в коммунистическую пиццерию!!</a>

        <form class="form-inline my-2 my-lg-0" action="{% url "login_view" %}" autocomplete="off" method="POST">
            {% csrf_token %}
            <div class="col-auto pl-0">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text "><i class="fa fa-user"></i></div>
                    </div>
                    <input type="text" class="form-control my-2 my-sm-0 mr-2" value="" placeholder="Номер телефона" name="number" required pattern="[0-9]*" autofocus maxlength="254" required id="id_number">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fa fa-lock"></i></div>
                    </div>
                    <input type="password" class="form-control my-2 my-sm-0" value="" placeholder="Пароль" type="password" name="password" required id="id_password">
                </div>
            </div>
            <div class="col-auto pl-0 pr-0">
                <button class="btn btn-outline-light my-2 my-sm-0 mr-2" type="submit">Войти!</button>
            </div>

        </form>
        <form>
            <a href="{% url "feedback_view" %}">
                <button class="btn" type="button">Отзывы</button>
            </a>
            <a href="{% url "register_view" %}">
                <button class="btn btn-outline-primary mx-1 my-xl-0 my-2" type="button">Зарегестрироваться!</button>
            </a>
        </form>

    </div>
{% endif %}
</div>
<div class="mt-2 col-md-12"></div>
{% block body %}{% endblock %}
</body>
</html>

onlinepizzas/templates/menu.html
{% extends "layout.html" %}

{% block body %}
    <form action= "{%  url  'confirm_order' %}" method="post">
    {% csrf_token %}
        <div class="container">
          <div class="text-center" style="padding-bottom: 15px;">
              <h3>Наше меню</h3>
              <h5>Выберите необходимые позиции</h5>
          </div>

          <table>
            <thead>
                <th scope="col">Пицца</th>
                <th scope="col">Цена</th>
                <th scope="col">Количество</th>
            </thead>
            {% for pizza in pizzas %}

                <tr>
                    <td>
                        <label for="{{pizza.name}}" style="font-size: x-large">{{pizza.name}}</label><br>
                        <label for="{{ pizza.description }}" style="font-size: large; font-style: italic;">{{ pizza.description }}</label>
                    </td>
                    <td><label for="{{ pizza.price }}">{{ pizza.price }} Руб. </label></td>
                    <input type="hidden" value="{{ pizza.price }}" name="price">
                    <td><input name="qty_pizza" class="qty" type="number" min="0" max="100" value="0"></td>
                </tr>

            {% endfor %}
          </table>
          <table>
            <thead>
                <th scope="col">Напитки</th>
                <th scope="col">Цена</th>
                <th scope="col">Количество</th>
            </thead>
            {% for drink in drinks %}

                <tr>
                    <td>
                        <label for="{{drink.name}}" style="font-size: x-large">{{drink.name}}</label><br>
                        <label for="{{ drink.description }}" style="font-size: large; font-style: italic;">{{ drink.description }}</label>
                    </td>
                    <td><label for="{{ drink.price }}">{{ drink.price }} Руб. </label></td>
                    <input type="hidden" value="{{ drink.price }}" name="price">
                    <td><input name="qty_drink" class="qty" type="number" min="0" max="100" value="0"></td>
                </tr>

            {% endfor %}
          </table>
          <table>
            <thead>
                <th scope="col">Закуски</th>
                <th scope="col">Цена</th>
                <th scope="col">Количество</th>
            </thead>
            {% for snack in snacks %}

                <tr>
                    <td>
                        <label for="{{snack.name}}" style="font-size: x-large">{{snack.name}}</label><br>
                        <label for="{{ snack.description }}" style="font-size: large; font-style: italic;">{{ snack.description }}</label>
                    </td>
                    <td><label for="{{ snack.price }}">{{ snack.price }} Руб. </label></td>
                    <input type="hidden" value="{{ snack.price }}" name="price">
                    <td><input name="qty_snack" class="qty" type="number" min="0" max="100" value="0"></td>
                </tr>

            {% endfor %}
          </table>
        <div class="text-center" style="padding-top: 20px; ">
          <button id="placeorder" type="submit" class="btn mx-1 my-xl-0 my-2" disabled
                  style="font-size: x-large;font-variant-caps: all-small-caps;"> Place Order </button>
        </div>

    </div>

{#    <script>#}
{#    function addQty(name) {#}
{#        if($('#Margarita').prop('checked')){#}
{#            let val = $('#qty_${name}').val();#}
{#            let set_val = parseInt(val) + 1#}
{#            $('#qty_{{ name }}').val(set_val);#}
{#        }#}
{#    }#}
{#    </script>#}
    </form>
{% endblock %}

onlinepizzas/templates/my_orders.html
{% extends "layout.html" %}

{% block body %}
    <div class="container">
      <div class="text-center" style="padding-bottom: 15px;">
        <h3>Ваша история заказов</h3>
      </div>

        {% if orders %}
            <a href="{% url "print_pdf" %}">
                <button class="btn mx-1 my-xl-0 my-2">PDF</button>
            </a>
            <table>
                <tbody>
                    {% for order,vals in orders.items %}
                        <tr>
                            <td>
                                <h5>Заказ от {{ vals.date}}</h5>

                                {% for val in vals.pizzas %}
                                    <label for="item">{{ val.itemId.name }} - {{ val.Qty }}</label><br>
                                {% endfor %}
                                {% for val in vals.drinks %}
                                    <label for="item">{{ val.itemId.name }} - {{ val.Qty }}</label><br>
                                {% endfor %}
                                {% for val in vals.snacks %}
                                    <label for="item">{{ val.itemId.name }} - {{ val.Qty }}</label><br>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <h2> У Вас нет заказов. Самое время это исправить!</h2>
        {% endif %}
    </div>
{% endblock %}

onlinepizzas/templates/order.html
{% extends "layout.html" %}

{% block body %}
<div class="container text-center" style="font-variant-caps: all-small-caps;">
    <div style="padding-bottom: 15px;font-size: x-large">The delicious pizzas you ordered are on your way. We hope you enjoy them :)</div>
    <label for="thankyoutext" style="font-style: italic;font-size: xx-large;">Thank you for your order and Happy Eating !!<br></label>
    <div>
        <p>Click below to see your order history</p>
        <a href="{% url "user_orders_view" %}">
            <button class="btn mx-1 my-xl-0 my-2">Order History</button>
        </a>
    </div>
</div>

{% endblock %}

onlinepizzas/templates/order_confirmation.html
{% extends "layout.html" %}
{% block body %}
    <form action= "{%  url  'place_order' %}" method="post">
    {% csrf_token %}
        <div class="container">
          <div class="text-center" style="padding-bottom: 15px;font-size: x-large;font-variant-caps: all-small-caps;">
            <h3>Проверьте заказ и заполните адресс доставки</h3>
          </div>
          <table>
            <thead>
            <tr>
                    <th scope="col">Позиция</th>
                    <th scope="col">Количество</th>
                    <th scope="col">Цена</th>
                </tr>
            </thead>
            {% for item, qty, price in pizzas_summary %}

                <tr>
                    <td><label for="{{item.name}}" style="font-size: x-large">{{ item.name }}</label><br>
                        <label for="{{ item.description }}" style="font-size: large; font-style: italic;">{{ item.description }}</label>
                    </td>
                    <input type="hidden" name="pizza" value="{{ item.name }}">
                    <td><label for="{{ qty }}">{{ qty }}</label> </td>
                    <input type="hidden" name="pizza_qty" value="{{ qty }}">
                    <td><label for="{{ price }}">{{ price }} РУБ</label></td>
                    <input type="hidden" name="price" value="{{ price }}">
                </tr>

            {% endfor %}
          {% for item, qty, price in drinks_summary %}

                <tr>
                    <td><label for="{{item.name}}" style="font-size: x-large">{{ item.name }}</label><br>
                        <label for="{{ item.description }}" style="font-size: large; font-style: italic;">{{ item.description }}</label>
                    </td>
                    <input type="hidden" name="drink" value="{{ item.name }}">
                    <td><label for="{{ qty }}">{{ qty }}</label> </td>
                    <input type="hidden" name="drink_qty" value="{{ qty }}">
                    <td><label for="{{ price }}">{{ price }} РУБ</label></td>
                    <input type="hidden" name="price" value="{{ price }}">
                </tr>

            {% endfor %}
          {% for item, qty, price in snacks_summary %}

                <tr>
                    <td><label for="{{item.name}}" style="font-size: x-large">{{ item.name }}</label><br>
                        <label for="{{ item.description }}" style="font-size: large; font-style: italic;">{{ item.description }}</label>
                    </td>
                    <input type="hidden" name="snack" value="{{ item.name }}">
                    <td><label for="{{ qty }}">{{ qty }}</label> </td>
                    <input type="hidden" name="snack_qty" value="{{ qty }}">
                    <td><label for="{{ price }}">{{ price }} РУБ</label></td>
                    <input type="hidden" name="price" value="{{ price }}">
                </tr>

            {% endfor %}

          </table>
        <div class="text-center" style="font-variant-caps: all-small-caps;">
            <label for="{{ grand_total }}" style="font-size: large; font-variant-caps: all-small-caps;">
                Цена доставки : 100 Рублей <br>
                Итоговая цена с учетом доставки: <strong>{{ grand_total }} РУБ</strong></label>
            <h4 >Укажите адресс доставки</h4><br>
            <table style="border: 0px !important;font-size: medium">
                <tr>
                    <td style="border: 0px !important;"><label for="address">Адресс:</label></td>
                    <td style="border: 0px !important;"><input type="text" placeholder="Улица, дом, квартира" required></td>
                </tr>
                <tr>
                    <td style="border: 0px !important;"><label for="telephone">Telephone Number:</label></td>
                    <td style="border: 0px !important;"><input type="tel" placeholder="phone number" required pattern="[0-9]*"></td>
                </tr>

            </table>
            <div class="text-center" style="padding-top: 20px; ">
                <button type="submit" style="font-size: x-large;font-variant-caps: all-small-caps;"> Заказать </button>
            </div>
        </div>


        </div>
    </form>
{% endblock %}